
export let arrayRus = ['лезвие','менопауза','сторона','ткань','резьба','описание',
                       'скунс','поправка','масло','трамвай','агентство','упражнение','проход','шоссе','рыба',
                       'чувство','сигнализация','лев','луг','лимфа','ящик','жвачка',
                       'десерт','печенье','сиденье','спираль','кресло','Мухаммед','устройство','церемония',
                       'покер','дождь','дискриминация','жирная кожа','стружка','кровать','дуб',
                       'граница','балласт','вещество','граффити','цепь','кристалл','шаттл','кремация',
                       'попугай','родственник','рыба','сюжет','позиция','фашизм','балкон','грипп',
                       'ветчина','игрушка','плита','кран','суфле','год','коллаж','сопротивление',
                       'крыльцо','масса','ворон','залог','брусника','йогурт','роса','бейсбол','сайты',
                       'странник',' станок','изобретение','клуб','календарь','коктейль','жена',
                       'зомби','салфетка','приложение','изделия','утро','велосипед','дрянь','брокколи',
                       'ключ','Пасха','ссылка','вышивание','мороженое','ярус','музыка','дуршлаг','ответ',
                       'канава','анемия','совесть','Англия','странник','антилопа','месяц','полет','подарок',
                       'приданое','фактура','объяснение','позор','хлопок','признание','мускул','лес','лимонад',
                       'количество','макароны','угорь','равновесие','макраме','Гарри','рабочий стол','рецепт','залог',
                       'стрельба','упражнение','свинина','мечеть','авокадо','стул','курсовой','гобелен','лук','вулкан',
                       'рис','стоянка такси','датчик','отек','глухота','брокколи','басня','Христос','комета',
                       'тиара','янтарь','почта','гора','забота','парад','ведро','полет','диарея','пример','нога',
                       'парапланеризм','язык','демон','аспирин','частота','ягуар','подтяжки','инстинкт','помощь',
                       'ворона','мисс','усилие','привязанность','переход','коврик','особняк','химия',
                       'дискриминация','враг','клятва','министр','корабль','печать','подсчет','кабель','ключ',
                       'ноябрь','уловка','печать','палантин','престиж','мишура','ласка','отец','урна','след','посещаемость',
                       'оригинал','носорог','оспа','месяц','лягушка','город','отпуск','оборудование','сокол','посудомойка',
                       'труп','лозунг','ракушка','посылка','обучение','акула','резинка','щитомордник','клетка',
                       'переключатель','завтрак','отверстие','захоронение','вымя','подросток','членство','пиво','пума','бумажник',
                       'особняк','арка','рука','мама','манго','способность','дискотека','полночь','гений','папа','нос','небо']


export let arrayEng = ['columnist', 'duty', 'misfortune', 'barberry', 'ecosystem', 'chimpanzee', 'letter',
                       'plateau', 'speech', 'politician', 'bank', 'packaging', 'evidence', 'dachshund',
                       'availability', 'lounge', 'responsibility', 'facing', 'abacus', 'fascism','martyr',
                       'gadfly','contact','horror','shoe','vow','trench','campfire','hinge','cover','lego',
                       'index','party','upstairs','birch','feather','lollipop','bus','brace','trouble','lamb',
                       'suite','income','eruption','rafting','shipment','conditioner','bricklayer','buggy',
                       'cosmetics','meteorite','cage','student','tower','degree','life','velcro','pretzel',
                       'diet','dill','possession','workbench','taurus','warehousing','cowberry','triangle',
                       'spoon','tea','toy','pine','nun','opponent','designer','wish','influence','fire station',
                       'payload','restriction','fever','mansion','toy','dinosaur','demography','hard shoulder',
                       'zebra crossing','solution','lamb','toll road','virtue','hickory','address','railroad crossing',
                       'reference','crosswalk','whisper','pie','basis','zebra','account','biomass','strike','worth',
                       'shopping centre','crack','acid','commentator','marble','ecology','vacation','marshal','privilege',
                       'eyeliner','sir','one-way','ash','track','w','finding','mountaineering','popcorn','freeway',
                       'compressor','background','asparagus','clothes','weasel','dactyl','opening','barrack','picnic',
                       'feather','starling','plates','windscreen','ward','polecat','poker','tendon','manifesto','airport',
                       'parrot','settlement','balm','thunder','clergy','antelope','apostle','neighbourhood','pie',
                       'competition','certificate','heron','gravity','bout','background','cleanser','bow','hierarchy',
                       'label','spy','republic','artery','hollywood','command','person','scissors','community','vendor',
                       'occupation','bridge','carrier','Rutabaga','publicity','brake','lifetime','crayfish','cargo','politics',
                       'aesthetics','hawk','suspicion','oscar','shape','boom','office','one-way','sake','communication','duty','director',
                       'text','instrument','element','beacon','commander','hotel','epithelium','pebble','turner','tradition','orbit',
                       'preface','article','atm','apricot','light','photograph','brick','memory','doctor','attic','sweetness','layout',
                       'peas','water bed','sheriff','freshman','dealer','stockings','politics','telescope','mutation','tombstone',
                       'joke','calamity','torpedo','jaw','miracle','park','trademark','label','glaze','limb','tissue','laundry basket',
                       'bond','license plate','watch','spice','spin','burner','piles','sense','Sunday','organ','melody','verisimilitude',
                       'railway','wound','seashore','soft drink','water','treasure','cuckoo','messiah','rafting','boarding','oyster',
                       'fake','grief','masonry','fire station','statement','daylight','coal','order','toe','snatch','catfish','string',
                       'staff meeting','fox','sally','deference','weed','commandment','destination','freedom','injury','roll','pirate',
                       'tumour','mousse','prostate','aura','pond','Language learning','puddle','dinnerware','hero','diploma','thrush',
                       'version','majority','plywood','spoke','analysis','baggage','appearance','suggestion','disorder','image','subway',
                       'bacteria','hole','insulation','porch','alloy','patience','youngster','wealth','stress','replacement','hubcap',
                       'dry skin','sir','time','outcome','niece','panther','w','quay','dwelling','score','stairway','engineer','hemisphere',
                       'dwelling place','synthesizer','road sign','compliment','hat','word','winemaking','pear','vampire','stewardess',
                       'replacement','injury','sweets','singer','lavatory','salary','pot','guard','demonstration','inauguration','neck',
                       'pudding','goal','helmet','comparison','cheque','taurus','bread','factor','spoon','relief','timetable','prisoner',
                       'position','crowd','monkey','hailstone','paradise','Hairpin turn','sawfish','importance','revenue','pasta','tension',
                       'cause','grid','omelette','priest','popover','formula','east','honey','pedestrian','refrigerator','sermon','entry',
                       'percentage','deal','hedgehog','hunting','stone','jig','destination','union','sunscreen','amenities ','marshmallow',
                       'slippers',' bookshop','instructor','solar eclipse','noun','carp','student','mistake','training','jail','anxiety',
                       'girlfriend','plumber','cod','layout','UV rays','retreat','postbox','singer','octopus','zodiac','flea','sergeant','drill']
 
